version: "3.8"

services:
    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"