spring:
  application:
    name: geobox

  security:
    user:
      name: ${APP_USER_NAME}
      password: ${APP_USER_PASSWORD}

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  key: ${JWT_SECRET}
  expiration-time: ${JWT_EXPIRATION}

server:
  address: 0.0.0.0
