spring:
  application:
    name: geobox

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  key: BI13LQPTvVnqkp81q79aQigMqCBpKSXaFSfeJzxQu81jO0ARnD63IsEyrgflgK8Ga23RjYbOVF12ZXFmhiMFlg==
  expiration-time: 86400000
